name: ok_multipl_poker
description: A game with basic multiplayer support.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  async: ^2.11.0
  audioplayers: ^6.0.0
  cloud_firestore: ^5.6.9
  collection: 1.19.1
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: 0.14.0
  equatable: ^2.0.7
  firebase_core: ^3.14.0
  firebase_auth: 5.7.0
  go_router: ^16.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  uuid: 4.5.2

  json_annotation: 4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  test: ^1.24.3

  build_runner: ^2.7.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/goblin_cards/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
